"use client";

import * as React from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useStore } from "@/store/store";
import { Panel, Button, Field, Banner, Disclaimer, StepBar, useToast, Pill } from "@/ui/primitives";
import type { NewCaseDraft } from "@/store/store";

const SECTIONS = ["Case identity", "Clinical picture", "Investigations", "Family & treatment"];

/** Next free reference in the ODY-### series. */
function nextCaseId(existing: string[]) {
  const nums = existing.map((id) => Number(id.replace(/\D/g, ""))).filter((n) => !Number.isNaN(n));
  const next = (nums.length ? Math.max(...nums) : 0) + 1;
  return `ODY-${String(next).padStart(3, "0")}`;
}

export default function NewCasePage() {
  const { state, dispatch } = useStore();
  const router = useRouter();
  const toast = useToast();
  const doctor = state.doctors[state.currentDoctorId!];
  const [step, setStep] = React.useState(0);

  const [draft, setDraft] = React.useState<NewCaseDraft>(() => ({
    id: nextCaseId(Object.keys(state.cases)),
    ageGroup: "Child · 4y",
    sex: "Female",
    country: doctor.country,
    phenotypeCluster: "Neurological",
    headline: "",
    narrative: "",
    geneticSummary: "",
    familyNotes: "",
    consanguinity: false,
    labNote: "",
    imagingNote: "",
    treatmentNote: "",
  }));

  const set = <K extends keyof NewCaseDraft>(k: K, v: NewCaseDraft[K]) => setDraft((d) => ({ ...d, [k]: v }));
  const canSubmit = draft.headline.trim().length > 3;

  const submit = () => {
    dispatch({ type: "createCase", draft });
    toast({ title: `Case ${draft.id} created`, body: "Next: upload a report so the assistant can propose phenotype terms." });
    router.push(`/cases/${draft.id}/verify`);
  };

  return (
    <>
      <header className="ody-rise og-between" style={{ alignItems: "flex-start", padding: "6px 4px 0" }}>
        <div style={{ maxWidth: "62ch" }}>
          <div className="og-row" style={{ gap: 10 }}>
            <Link href="/cases" className="og-small og-link">Cases</Link>
            <span className="og-small" aria-hidden>/</span>
            <span className="og-small">New case</span>
          </div>
          <h1 className="og-h1" style={{ marginTop: 12 }}>Create case</h1>
          <p className="og-lede" style={{ marginTop: 10 }}>
            Only what makes a case comparable. Everything else stays in your hospital system — ODYSSEY holds structured
            signals, never a medical record.
          </p>
        </div>
        <Disclaimer />
      </header>

      <div className="og-sec">
        <Panel glass><StepBar stages={SECTIONS} index={step} /></Panel>
      </div>

      <div className="og-sec og-grid" data-cols="side">
        <Panel title={SECTIONS[step]} meta={`Section ${step + 1} of ${SECTIONS.length}`}>
          {step === 0 && (
            <div className="og-stack">
              <div className="og-grid" data-cols="2">
                <Field label="Case reference" hint="Generated by the network. Pseudonymous — never a patient identifier.">
                  <input className="og-input og-mono" value={draft.id} readOnly />
                </Field>
                <Field label="Country">
                  <input className="og-input" value={draft.country} onChange={(e) => set("country", e.target.value)} />
                </Field>
              </div>
              <div className="og-grid" data-cols="2">
                <Field label="Age group" hint="Banded, to prevent re-identification.">
                  <select className="og-select" value={draft.ageGroup} onChange={(e) => set("ageGroup", e.target.value)}>
                    {["Infant · <1y", "Infant · 9m", "Child · 2y", "Child · 4y", "Child · 7y", "Adolescent · 13y", "Adult"].map((a) => <option key={a}>{a}</option>)}
                  </select>
                </Field>
                <Field label="Sex">
                  <select className="og-select" value={draft.sex} onChange={(e) => set("sex", e.target.value)}>
                    {["Female", "Male", "Not recorded"].map((a) => <option key={a}>{a}</option>)}
                  </select>
                </Field>
              </div>
              <Field label="Phenotype cluster" hint="The broad system involved. Used to narrow the federated query.">
                <select className="og-select" value={draft.phenotypeCluster} onChange={(e) => set("phenotypeCluster", e.target.value)}>
                  {["Neurological", "Metabolic", "Neuromuscular", "Hepatic", "Cardiac", "Immune", "Movement disorder", "Ophthalmic", "Dermatologic", "Multisystem"].map((a) => <option key={a}>{a}</option>)}
                </select>
              </Field>
              <Banner tone="plain">
                Submitting institution: <b>{doctor.institution}</b>, {doctor.city}. Consent for cross-border comparison
                is recorded at your site; this demonstration assumes it is on file.
              </Banner>
            </div>
          )}

          {step === 1 && (
            <div className="og-stack">
              <Field label="One-line presentation" hint="How you would describe this case to a colleague in a corridor.">
                <input className="og-input" placeholder="e.g. Progressive infantile encephalopathy of unknown cause" value={draft.headline} onChange={(e) => set("headline", e.target.value)} />
              </Field>
              <Field label="Clinical history" hint="Free text. Structured signals come from the document you upload next.">
                <textarea className="og-textarea" rows={6} placeholder="Course from birth to present: onset, plateau, regression, investigations…" value={draft.narrative} onChange={(e) => set("narrative", e.target.value)} />
              </Field>
              <Banner>
                Phenotype terms are added in the next step, where an uploaded report is parsed and every proposed term
                is put to you for confirmation.
              </Banner>
            </div>
          )}

          {step === 2 && (
            <div className="og-stack">
              <Field label="Genetics" hint="Tests performed and any reported variants, in HGVS where available. Raw sequence data never leaves your institution.">
                <textarea className="og-textarea" rows={3} placeholder="e.g. Trio exome non-diagnostic; NDUFAF6 c.532G>C heterozygous, VUS" value={draft.geneticSummary} onChange={(e) => set("geneticSummary", e.target.value)} />
              </Field>
              <Field label="Laboratory" hint="Key abnormal analytes with units.">
                <input className="og-input" placeholder="e.g. Plasma lactate 4.1 mmol/L, alanine 648 µmol/L" value={draft.labNote} onChange={(e) => set("labNote", e.target.value)} />
              </Field>
              <Field label="Imaging" hint="Structured findings. Images stay at the originating site.">
                <input className="og-input" placeholder="e.g. Bilateral putaminal T2 hyperintensity" value={draft.imagingNote} onChange={(e) => set("imagingNote", e.target.value)} />
              </Field>
            </div>
          )}

          {step === 3 && (
            <div className="og-stack">
              <Field label="Family history" hint="Pedigree structure, affected relatives, ancestry.">
                <textarea className="og-textarea" rows={3} placeholder="e.g. Two affected among four siblings; parents unaffected" value={draft.familyNotes} onChange={(e) => set("familyNotes", e.target.value)} />
              </Field>
              <label className="og-check">
                <input type="checkbox" checked={draft.consanguinity} onChange={(e) => set("consanguinity", e.target.checked)} />
                Consanguinity reported
              </label>
              <Field label="Treatment response" hint="Interventions with measured response — often a strong matching signal.">
                <input className="og-input" placeholder="e.g. Ketogenic diet, ~40% seizure reduction" value={draft.treatmentNote} onChange={(e) => set("treatmentNote", e.target.value)} />
              </Field>
              <Banner tone="amber">
                <b>Synthetic data only.</b> Do not enter information about a real patient in this demonstration.
              </Banner>
            </div>
          )}

          <div className="og-between" style={{ marginTop: 22 }}>
            <Button variant="ghost" onClick={() => setStep((s) => Math.max(0, s - 1))} disabled={step === 0}>Back</Button>
            {step < SECTIONS.length - 1 ? (
              <Button onClick={() => setStep((s) => s + 1)}>Continue</Button>
            ) : (
              <Button onClick={submit} disabled={!canSubmit}>Create case &amp; upload report</Button>
            )}
          </div>
          {step === SECTIONS.length - 1 && !canSubmit && (
            <p className="og-small" style={{ marginTop: 10, color: "var(--amber)" }}>
              A one-line presentation is required — go back to “Clinical picture”.
            </p>
          )}
        </Panel>

        <aside className="og-stack">
          <Panel glass title="Case preview">
            <div className="og-row" style={{ gap: 10 }}>
              <span className="og-mono" style={{ fontSize: 16, fontWeight: 700 }}>{draft.id}</span>
              <Pill tone="amber">Unresolved</Pill>
            </div>
            <p style={{ fontSize: 14, marginTop: 10, color: "var(--ink-2)" }}>
              {draft.headline || <span style={{ color: "var(--ink-4)" }}>No presentation entered yet</span>}
            </p>
            <dl className="og-kv" style={{ marginTop: 14 }}>
              <dt>Country</dt><dd>{draft.country}</dd>
              <dt>Age</dt><dd>{draft.ageGroup}</dd>
              <dt>Sex</dt><dd>{draft.sex}</dd>
              <dt>Cluster</dt><dd>{draft.phenotypeCluster}</dd>
            </dl>
          </Panel>
          <Panel title="What happens next">
            <ol style={{ margin: 0, paddingLeft: 18, fontSize: 13, lineHeight: 1.85, color: "var(--ink-2)" }}>
              <li>Upload a synthetic clinical report</li>
              <li>The assistant proposes phenotype terms with sources</li>
              <li>You confirm, edit or remove each one</li>
              <li>The case is matched against the network</li>
            </ol>
          </Panel>
        </aside>
      </div>
    </>
  );
}
