/**
 * Build-time only: derive a simplified equirectangular world geometry so the
 * network visualisations use real coastlines instead of a decorative blob.
 * Output is committed as src/data/world.ts; this script is not part of runtime.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";
import { geoPath, geoEquirectangular, geoContains } from "d3-geo";

const topo = JSON.parse(readFileSync("node_modules/world-atlas/land-110m.json", "utf8"));
const land = feature(topo, topo.objects.land);

// viewBox 0 0 100 50 — matches project() in src/data/odyssey.ts
const projection = geoEquirectangular().scale(100 / (2 * Math.PI)).translate([50, 25]);
const path = geoPath(projection);
const round = (s) => s.replace(/-?\d+\.?\d*/g, (n) => String(Math.round(parseFloat(n) * 100) / 100));
const outline = round(path(land));

// Dot matrix: one dot per land cell on a 1.6-degree-ish grid, for the
// "dotted world" treatments. Stored as compact [x,y] pairs in viewBox space.
const dots = [];
for (let lat = 82; lat >= -58; lat -= 3.1) {
  for (let lon = -180; lon <= 180; lon += 3.1) {
    if (geoContains(land, [lon, lat])) {
      const [x, y] = projection([lon, lat]);
      dots.push([Math.round(x * 10) / 10, Math.round(y * 10) / 10]);
    }
  }
}

const out = `/* Generated by scripts/build-world.mjs — do not edit by hand.
   Simplified Natural Earth land geometry, equirectangular, viewBox "0 0 100 50". */

export const WORLD_PATH = ${JSON.stringify(outline)};

export const WORLD_DOTS: [number, number][] = ${JSON.stringify(dots)};
`;
writeFileSync("src/data/world.ts", out);
console.log("world.ts:", (out.length / 1024).toFixed(1), "kB,", dots.length, "dots");
